@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_acount
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "Leonardo do Nascimento",
  "email": "leonardo3.nascimento@gmail.com",
  "password": "102030"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "leonardo3.nascimento@gmail.com",
  "password": "102030"
}

###

# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

 {
  "title": "nova pergunta",
  "content": "conteúdo da pergunta"
 }

###

# @name fetch_recent_questions
GET {{baseURL}}/questions?page=1
Authorization: Bearer {{authToken}}
